
# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

name = "cloudflare-login-worker"
type = "javascript"

account_id = "f0c92755958332f29a4d8658606c6f34"
workers_dev = true
compatibility_date = "2024-10-16"

[env.production]
name = "cloudflare-login-worker"
type = "javascript"
account_id = "f0c92755958332f29a4d8658606c6f34ID"
workers_dev = false
route = "https://tournet.com/*"
zone_id = "7953fd5d77fce8a01ae84db1a6c243e9"

[[d1_databases]]
binding = "DB"  # Corrected binding name
database_name = "d1-tn-hosts"
