name = "pub-sub"
compatibility_date = "2024-08-18"
account_id = "f0c92755958332f29a4d8658606c6f34"
workers_dev = true

[durable_objects]
bindings = [
  { name = "MY_DURABLE_OBJECT", class_name = "MyDurableObject" }
]

[[kv_namespaces]]
binding = "VENDOR_CONVERSATIONS"
id = "0aee54799aaa4687ab64e3e457a65243"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["MyDurableObject"]
